export declare const DEFAULT_METRIC_WINDOW_SECONDS = 60;
export declare const ERROR_COUNT_THRESHOLD = 10;
export declare const SERVICE_DOWNTIME_MINUTES = 5;
export declare const LATENCY_THRESHOLD_MS = 1000;
export declare const LOG_RETENTION_DAYS = 30;
export declare const BATCH_INSERT_SIZE = 1000;
export declare const ALERT_RETRY_ATTEMPTS = 3;
export declare const DEFAULT_TRACE_SAMPLE_RATE = 1;
export declare const TRACE_SAMPLE_RATE_ERROR = 1;
//# sourceMappingURL=constants.d.ts.map